---
datalab_scraper_container_name: datalab-scraper
datalab_scraper_image_name: datalab-scraper
datalab_scraper_host_config_path: "{{ ansible_user_home_dir }}/datalab_scraper/config.yaml"
datalab_scraper_container_config_path: /app/config.yaml
