---
- name: Synchronize nginx files to remote
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_home_dir }}/nginx"
    delete: true

- name: Make directory for rendered templates
  ansible.builtin.file:
    path: "{{ ansible_user_home_dir }}/nginx/rendered/include"
    state: directory
    mode: "0755"

- name: Render templated datalab config
  ansible.builtin.template:
    src: nginx_datalab.conf.j2
    dest: "{{ ansible_user_home_dir }}/nginx/rendered/include/nginx_datalab.conf"
    mode: "0644"

- name: Render templated SSL config
  ansible.builtin.template:
    src: nginx_ssl.conf.j2
    dest: "{{ ansible_user_home_dir }}/nginx/rendered/nginx_ssl.conf"
    mode: "0644"

- name: Build nginx image
  community.docker.docker_image:
    name: datalab-nginx
    source: build
    state: present
    force_source: true
    build:
      path: "{{ ansible_user_home_dir }}/nginx"

- name: Launch nginx container
  community.docker.docker_container:
    name: datalab-nginx
    image: datalab-nginx
    network_mode: host
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
      #- certbot-conf:/etc/ssl/datalab
#      - certbot-www:/var/www/certbot
    restart_policy: always
